### ISSUE TITLE
Can't download audio encoder

### ISSUE THREAD

**Issue by YangZyyyy** [HITsz-TMG/UMOE-Scaling-Unified-Multimodal-LLMs#3]
Can't download `[Fine-tuned BEATs_iter3+ (AS2M)](https://valle.blob.core.windows.net/share/BEATs/BEATs_iter3_plus_AS2M.pt?sv=2020-08-04&st=2023-03-01T07%3A51%3A05Z&se=2033-03-02T07%3A51%3A00Z&sr=c&sp=rl&sig=QJXmSJG9DbMKf48UDIU1MfzIro8HQOf3sqlNXiflY1I%3D)`

The link is inaccessible. There is  the error report:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AuthenticationFailed</Code>
<Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:2fcc9820-701e-003e-1003-b0562d000000 Time:2024-05-27T07:03:18.3397596Z</Message>
<AuthenticationErrorDetail>Signature did not match. String to sign used was rl 2023-03-01T07:51:05Z 2033-03-02T07:51:00Z /blob/valle/share 2020-08-04 c </AuthenticationErrorDetail>
</Error>
```

 Is there a Huggingface link for this Encoder?

**Comment by expapa** [comment]
The link for the BEATs encoder has been updated to the latest version and is available for download now. Thanks for your reminder.

**Comment by expapa** [comment]
> Can't download `[Fine-tuned BEATs_iter3+ (AS2M)](https://valle.blob.core.windows.net/share/BEATs/BEATs_iter3_plus_AS2M.pt?sv=2020-08-04&st=2023-03-01T07%3A51%3A05Z&se=2033-03-02T07%3A51%3A00Z&sr=c&sp=rl&sig=QJXmSJG9DbMKf48UDIU1MfzIro8HQOf3sqlNXiflY1I%3D)`
> 
> The link is inaccessible. There is the error report:
> 
> ```
> This XML file does not appear to have any style information associated with it. The document tree is shown below.
> <Error>
> <Code>AuthenticationFailed</Code>
> <Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:2fcc9820-701e-003e-1003-b0562d000000 Time:2024-05-27T07:03:18.3397596Z</Message>
> <AuthenticationErrorDetail>Signature did not match. String to sign used was rl 2023-03-01T07:51:05Z 2033-03-02T07:51:00Z /blob/valle/share 2020-08-04 c </AuthenticationErrorDetail>
> </Error>
> ```
> 
> Is there a Huggingface link for this Encoder?

The link for the BEATs encoder has been updated to the latest version and is available for download now. Thanks for your reminder.

**Comment by YangZyyyy** [comment]
Thanks for your response. I have successfully run the inference code for Uni_MoE_audio. The model works and it can describe the audio. What I am more interested in is the speech-to-text model. When the base model for speech will be uploaded? Thanks for your great work!
